=== cccwam/ift6759-project1-public/configs/admin/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "dataframe_path": {
      "type": "string"
    },
    "start_bound": {
      "type": "string"
    },
    "end_bound": {
      "type": "string"
    },
    "stations": {
      "type": "object",
      "properties": {
        "BND": {
          "type": "array"
        },
        "TBL": {
          "type": "array"
        },
        "DRA": {
          "type": "array"
        },
        "FPK": {
          "type": "array"
        },
        "GWN": {
          "type": "array"
        },
        "PSU": {
          "type": "array"
        },
        "SXF": {
          "type": "array"
        }
      },
      "required": [
        "BND",
        "TBL",
        "DRA",
        "FPK",
        "GWN",
        "PSU",
        "SXF"
      ],
      "additionalProperties": false
    },
    "target_time_offsets": {
      "type": "array"
    },
    "target_datetimes": {
      "type": "array"
    }
  },
  "required": [
    "dataframe_path",
    "start_bound",
    "end_bound",
    "stations",
    "target_time_offsets",
    "target_datetimes"
  ],
  "additionalProperties": false
}

=== cccwam/ift6759-project1-public/configs/admin/hourly_sample_daytime_20_validation.json
{"dataframe_path": "/project/cq-training-1/project1/data/catalog.helios.public.20100101-20160101.pkl", "start_bound": "2010-01-01", "end_bound": "2015-12-31", "stations": {"BND": [40.05192, -88.37309, 230], "TBL": [40.12498, -105.2368, 1689], "DRA": [36.62373, -116.01947, 1007], "FPK": [48.30783, -105.1017, 634], "GWN": [34.2547, -89.8729, 98], "PSU": [40.72012, -77.93085, 376], "SXF": [43.73403, -96.62328, 473]}, "target_time_offsets": ["P0DT0H0M0S", "P0DT1H0M0S", "P0DT3H0M0S", "P0DT6H0M0S"], "target_datetimes": ["2014-08-06T18:30:00", "2014-07-06T12:30:00", "2014-05-16T22:30:00", "2014-02-23T16:45:00", "2014-08-18T15:15:00", "2014-02-20T17:30:00", "2014-06-19T01:30:00", "2014-09-29T13:00:00", "2014-08-21T07:30:00", "2014-12-18T12:45:00", "2014-03-17T12:45:00", "2014-12-08T14:15:00", "2014-12-04T23:00:00", "2014-09-10T00:45:00", "2014-03-24T16:45:00", "2014-03-16T20:30:00", "2014-06-27T23:00:00", "2014-05-11T16:00:00", "2014-05-29T18:30:00", "2014-11-03T15:15:00", "2014-06-24T02:45:00", "2014-02-27T18:15:00", "2014-04-13T18:15:00", "2014-10-08T17:30:00", "2014-07-11T23:00:00", "2014-04-02T13:30:00", "2014-01-12T13:15:00", "2014-11-28T12:45:00", "2014-06-20T01:30:00", "2014-04-21T12:30:00", "2014-07-28T01:45:00", "2014-04-16T18:30:00", "2014-03-12T00:45:00", "2014-03-14T16:15:00", "2014-06-23T00:15:00", "2014-06-25T00:15:00", "2014-07-16T23:00:00", "2014-01-28T22:15:00", "2014-11-10T20:30:00", "2014-04-12T19:45:00", "2014-03-22T21:15:00", "2014-09-07T18:45:00", "2014-12-24T12:45:00", "2014-08-20T21:15:00", "2014-06-03T09:45:00", "2014-07-02T10:15:00", "2014-06-14T09:45:00", "2014-10-29T14:30:00", "2014-02-09T12:15:00", "2014-01-12T15:15:00"]}
